version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: btc-deepsea_deepsea_1
      APP_PORT: 5000

  deepsea:
    image: ghcr.io/retropex/custom-dashboard-ocean:v0.8.1@sha256:6b5144ed7e7ebfbfed7706bbb932d62689df67bd188951eb92f201690eedce8f
    user: 1000:1000
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/:/app/data/
    ports:
      - 5000:5000