version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_MEMPOOL_IP
      APP_PORT: $APP_MEMPOOL_PORT
      PROXY_AUTH_ADD: "false"
      AUDIT: "true"
      MAINNET_BLOCK_AUDIT_START_HEIGHT: "840000"
  web:
    image: ghcr.io/retropex/mempoolfrontend@sha256:dda9a91a1cc745373f36f7d4644480b19f787fa09040e3a78404ce0e3416f556
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for mariadb:3306 --timeout=720 -- nginx -g 'daemon off;'"
    environment:
      FRONTEND_HTTP_PORT: $APP_MEMPOOL_PORT
      BACKEND_MAINNET_HTTP_HOST: $APP_MEMPOOL_API_IP
      NGINX_PORT: $APP_MEMPOOL_PORT
      NGINX_HOSTNAME: $APP_MEMPOOL_API_IP
      LIGHTNING_DETECTED_PORT: $APP_LIGHTNING_NODE_PORT
    networks:
      default:
        ipv4_address: $APP_MEMPOOL_IP
  api:
    image: ghcr.io/retropex/mempoolbackend@sha256:56eadf56c9334c2e10e28019c34ba80cd3069abc44655c1150b93820b4f7042e
    user: "1000:1000"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh mariadb:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ${APP_DATA_DIR}/data:/backend/cache
      - ${UMBREL_ROOT}/app-data/lightning/data/lnd:/lnd:ro
    environment:
      CORE_RPC_HOST: $APP_BITCOIN_NODE_IP
      CORE_RPC_PORT: $APP_BITCOIN_RPC_PORT
      CORE_RPC_USERNAME: $APP_BITCOIN_RPC_USER
      CORE_RPC_PASSWORD: $APP_BITCOIN_RPC_PASS
      MEMPOOL_BACKEND: "none"
      DATABASE_HOST: $APP_MEMPOOL_DB_IP
      DATABASE_PORT: "3306"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      MEMPOOL_HTTP_PORT: "8999"
      MEMPOOL_CACHE_DIR: "/backend/cache"
      MEMPOOL_CLEAR_PROTECTION_MINUTES: "20"
      MEMPOOL_STDOUT_LOG_MIN_PRIORITY: "info"
      LIGHTNING_ENABLED: "false"
      LIGHTNING_BACKEND: "lnd"
      LIGHTNING_STATS_REFRESH_INTERVAL: 3600
      LIGHTNING_GRAPH_REFRESH_INTERVAL: 3600
      LND_TLS_CERT_PATH: "/lnd/tls.cert"
      LND_MACAROON_PATH: "/lnd/data/chain/bitcoin/$APP_BITCOIN_NETWORK/readonly.macaroon"
      LND_REST_API_URL: "https://$APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_REST_PORT"
      LND_TIMEOUT: 120000
      STATISTICS_ENABLED: "true"
      MEMPOOL_ADVANCED_GBT_MEMPOOL: "true"
      MEMPOOL_ADVANCED_GBT_AUDIT: "true"
      MEMPOOL_BLOCKS_SUMMARIES_INDEXING: "true"
      MEMPOOL_INDEXING_BLOCKS_AMOUNT: "true"
      MEMPOOL_CPFP_INDEXING: "true"
      MEMPOOL_AUDIT: "true"
      MEMPOOL_MEMPOOL_BLOCKS_AMOUNT: "50"
      REPLICATION_ENABLED: "false"
      MEMPOOL_GOGGLES_INDEXING: "true"
    networks:
       default:
         ipv4_address: $APP_MEMPOOL_API_IP
  mariadb:
    image: mariadb:10.5.12@sha256:dfcba5641bdbfd7cbf5b07eeed707e6a3672f46823695a0d3aba2e49bbd9b1dd
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "moneyprintergobrrr"
    networks:
       default:
         ipv4_address: $APP_MEMPOOL_DB_IP
